---
heartbeat.monitors:
- type: browser
  id: my-monitor
  name: My Monitor
  schedule: "@every 1m"
  source:
    inline:
      script: |-
        step("load homepage", async () => {
            await page.goto('https://www.elastic.co');
        });
        step("hover over products menu", async () => {
            await page.hover('css=[data-nav-item=products]');
        });
- type: browser
  id: todos
  name: Todos
  schedule: "@every 1m"
  source:
    local:
      path: "/opt/elastic-synthetics/examples/todos"